apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: port-k8s-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://port-labs.github.io/helm-charts
    chart: port-k8s-exporter
    targetRevision: 0.3.20
    helm:
      values: |
        secret:
          useExistingSecret: true
          name: port-credentials
        overwriteConfigurationOnRestart: true
        stateKey: dot
        extraEnv:
          - name: CLUSTER_NAME
            value: dot
        createMissingRelatedEntities: true
        configMap:
          config:
            resources:
              - kind: v1/namespaces
                selector:
                  query: .metadata.name | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"argocdNamespace"'
                        properties:
                          createdAt: .metadata.creationTimestamp
                        relations:
                          cluster: env.CLUSTER_NAME
              - kind: apps/v1/deployments
                selector:
                  query: .metadata.namespace | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"workload"'
                        properties:
                          version: .spec.template.spec.containers[0].image | split(":") | last
                        relations:
                          namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              - kind: devopstoolkit.live/v1beta1/apps
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"crossplaneApp"'
                        properties:
                          image: .spec.image
                          tag: .spec.tag
                          host: .status.host // .spec.host
                          port: .spec.port
                          scalingEnabled: .spec.scaling.enabled
                          scalingMin: .spec.scaling.min
                          scalingMax: .spec.scaling.max
                          composition: .spec.crossplane.compositionRef.name
                          syncStatus: .status.conditions[] | select(.type == "Synced") | .status
                          readyStatus: .status.conditions[] | select(.type == "Ready") | .status
                          creationTimestamp: .metadata.creationTimestamp
                          labels: .metadata.labels
                        relations:
                          namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
              - kind: devopstoolkit.live/v1beta1/sqls
                selector:
                  query: "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
                        title: .metadata.name
                        blueprint: '"crossplaneSql"'
                        properties:
                          provider: .spec.crossplane.compositionSelector.matchLabels.provider
                          region: .spec.region
                          size: .spec.size
                          version: .spec.version
                          composition: .spec.crossplane.compositionRef.name
                          syncStatus: .status.conditions[] | select(.type == "Synced") | .status
                          readyStatus: .status.conditions[] | select(.type == "Ready") | .status
                          creationTimestamp: .metadata.creationTimestamp
                        relations:
                          namespace: .metadata.namespace + "-" + env.CLUSTER_NAME
  destination:
    server: https://kubernetes.default.svc
    namespace: port-k8s-exporter
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
